### ISSUE TITLE
Is imagestore compatible with django cms 3.2? 

### ISSUE THREAD

**Issue by holms** [hovel/imagestore#62]
I have a 3.2 version of djangocms, I'm unable to find imagestore in plugin list of djangocms, from structure menu of some placeholder.

I'm I doing something wrong? I've done everything as stated in [documentation](http://imagestore.readthedocs.org/en/latest/djangocms.html)

**Comment by holms** [comment]
Solved.

**Comment by lampslave** [comment]
Unfortunately, we do not use django cms in our projects, so I don't know what's going on. #37 is not merged yet for the same reason.
