### ISSUE TITLE
Could you pls update to Django 1.10?

### ISSUE THREAD

**Issue by TitanFighter** [hovel/imagestore#67]
When saving image, error appears:

```
Exception Value: Cannot force an update in save() with no primary key.
Exception Location: /home/simsim/www/testproject/lib/python3.5/site-packages/django/db/models/base.py in _save_table, line 880
```

With Django 1.9.9 everything is ok

Thank you.

**Comment by lampslave** [comment]
What version are you using? Try install it from current master branch.

**Comment by TitanFighter** [comment]
When I tried to use imagestore 6 months ago, I tried with master branch.

**Comment by lampslave** [comment]
Yes, but all tests passed with 1.10 https://travis-ci.org/hovel/imagestore/builds/216934436

**Comment by TitanFighter** [comment]
Strange. Initially I added Imagestore to my existing project which was based on Django 1.10. When I got the error above, If I remember correctly, I rechecked using fresh instalation of Django 1.10 and got the same error.

**Comment by lampslave** [comment]
Maybe it was a bug in django? https://code.djangoproject.com/ticket/27419
Anyway I need more info to reproduce.

**Comment by TitanFighter** [comment]
I will check again later this week and inform you.

**Comment by lampslave** [comment]
Release 3.0.0 on pypi. 1.10 pass all tests. Feel free to reopen if need.
